# Generated by Django 4.2.7 on 2024-02-18 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shop_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='img_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shop',
            name='rating',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.CharField(default='', max_length=255),
        ),
    ]
